APP_NAME="Copyus"
APP_ENV=production
APP_KEY=base64:68vWhdy7nEaVfc0IKI70mPg9d4kn1drfn3qkBLZ2idw=
APP_DEBUG=false
APP_URL=https://copyus.es

APP_LOCALE=ca
APP_FALLBACK_LOCALE=es
APP_FAKER_LOCALE=ca_ES

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

# PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=copyuses_shop
DB_USERNAME=copyuses_shop
DB_PASSWORD=fN$2AmztAbVGKv4S
DB_SOCKET=

SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database
# CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_SCHEME=null
MAIL_HOST=mailpit
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_FROM_ADDRESS="noreply@copyus.es"
MAIL_FROM_NAME="Copyus"


AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"

# Anthropic / Claude AI
ANTHROPIC_API_KEY= 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
ANTHROPIC_MODEL=claude-haiku-4-5-20251001
